"""Public exports for the IR normalisation pipeline."""

from .model import (
    IRAsciiHeader,
    IRAsciiPreamble,
    IRAsciiWrapperCall,
    IRBlock,
    IRBuildArray,
    IRBuildMap,
    IRBuildTuple,
    IRCall,
    IRCallPreparation,
    IRCallReturn,
    IRLiteral,
    IRLiteralBlock,
    IRLiteralChunk,
    IRLoad,
    IRNode,
    IRProgram,
    IRRaw,
    IRReturn,
    IRSegment,
    IRSlot,
    IRStackDrop,
    IRStackDuplicate,
    IRStore,
    IRTailcallAscii,
    IRTailcallFrame,
    IRTablePatch,
    IRTestSetBranch,
    IRTruthTest,
    IRIf,
    IRFunctionPrologue,
    MemSpace,
    NormalizerMetrics,
)
from .normalizer import IRNormalizer
from .printer import IRTextRenderer

__all__ = [
    "IRNormalizer",
    "IRTextRenderer",
    "IRProgram",
    "IRSegment",
    "IRBlock",
    "IRCall",
    "IRReturn",
    "IRBuildArray",
    "IRBuildMap",
    "IRBuildTuple",
    "IRLiteralBlock",
    "IRLiteral",
    "IRLiteralChunk",
    "IRAsciiWrapperCall",
    "IRTailcallAscii",
    "IRFunctionPrologue",
    "IRIf",
    "IRTruthTest",
    "IRTestSetBranch",
    "IRAsciiHeader",
    "IRCallReturn",
    "IRLoad",
    "IRStore",
    "IRStackDuplicate",
    "IRStackDrop",
    "IRAsciiPreamble",
    "IRCallPreparation",
    "IRTailcallFrame",
    "IRTablePatch",
    "IRSlot",
    "IRRaw",
    "MemSpace",
    "NormalizerMetrics",
]
